/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAssociateendpointCollectionResponseAssociate.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   associateendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAssociateendpointCollectionResponseAssociate (0 custom class methods, 2 custom properties)

#import "GTLAssociateendpointCollectionResponseAssociate.h"

#import "GTLAssociateendpointAssociate.h"

// ----------------------------------------------------------------------------
//
//   GTLAssociateendpointCollectionResponseAssociate
//

@implementation GTLAssociateendpointCollectionResponseAssociate
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLAssociateendpointAssociate class]
                                forKey:@"items"];
  return map;
}

@end
