/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAssociateendpointAssociate.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   associateendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAssociateendpointAssociate (0 custom class methods, 9 custom properties)

#import "GTLAssociateendpointAssociate.h"

// ----------------------------------------------------------------------------
//
//   GTLAssociateendpointAssociate
//

@implementation GTLAssociateendpointAssociate
@dynamic capacity, cernerId, cernerTeam, email, identifier, mobile, musicGenre,
         name, vehicleModel;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

@end
