/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAssociateendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   associateendpoint/v1
// Description:
//   This is an API

#import "GTLAssociateendpointConstants.h"

#import "GTLAssociateendpointAssociate.h"
#import "GTLAssociateendpointCollectionResponseAssociate.h"

#import "GTLQueryAssociateendpoint.h"
#import "GTLServiceAssociateendpoint.h"
