/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAssociateendpointCollectionResponseAssociate.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   associateendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAssociateendpointCollectionResponseAssociate (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLAssociateendpointAssociate;

// ----------------------------------------------------------------------------
//
//   GTLAssociateendpointCollectionResponseAssociate
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLAssociateendpointCollectionResponseAssociate : GTLCollectionObject
@property (retain) NSArray *items;  // of GTLAssociateendpointAssociate
@property (copy) NSString *nextPageToken;
@end
