/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAssociateendpointAssociate.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   associateendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLAssociateendpointAssociate (0 custom class methods, 9 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLAssociateendpointAssociate
//

@interface GTLAssociateendpointAssociate : GTLObject
@property (retain) NSNumber *capacity;  // intValue
@property (copy) NSString *cernerId;
@property (copy) NSString *cernerTeam;
@property (copy) NSString *email;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (copy) NSString *mobile;
@property (copy) NSString *musicGenre;
@property (copy) NSString *name;
@property (copy) NSString *vehicleModel;
@end
