/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLAssociateendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   associateendpoint/v1
// Description:
//   This is an API

#import "GTLAssociateendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeAssociateendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
