/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLCarpoolendpointCollectionResponseCarPool.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   carpoolendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLCarpoolendpointCollectionResponseCarPool (0 custom class methods, 2 custom properties)

#import "GTLCarpoolendpointCollectionResponseCarPool.h"

#import "GTLCarpoolendpointCarPool.h"

// ----------------------------------------------------------------------------
//
//   GTLCarpoolendpointCollectionResponseCarPool
//

@implementation GTLCarpoolendpointCollectionResponseCarPool
@dynamic items, nextPageToken;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLCarpoolendpointCarPool class]
                                forKey:@"items"];
  return map;
}

@end
