/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLCarpoolendpointCarPool.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   carpoolendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLCarpoolendpointCarPool (0 custom class methods, 13 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLCarpoolendpointCarPool
//

@interface GTLCarpoolendpointCarPool : GTLObject
@property (retain) NSNumber *capcaity;  // intValue

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (copy) NSString *descriptionProperty;

@property (retain) NSNumber *destinationLatitude;  // doubleValue
@property (copy) NSString *destinationLocation;
@property (retain) NSNumber *destinationLongitude;  // doubleValue
@property (copy) NSString *driverId;
@property (copy) NSString *driverName;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (retain) NSNumber *originLatitude;  // doubleValue
@property (copy) NSString *originLocation;
@property (retain) NSNumber *originLongitude;  // doubleValue
@property (retain) GTLDateTime *startDateTime;
@property (copy) NSString *status;
@end
