/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLCarpoolendpointCarPoolCollection.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   carpoolendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLCarpoolendpointCarPoolCollection (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLCarpoolendpointCarPool;

// ----------------------------------------------------------------------------
//
//   GTLCarpoolendpointCarPoolCollection
//

// This class supports NSFastEnumeration over its "items" property. It also
// supports -itemAtIndex: to retrieve individual objects from "items".

@interface GTLCarpoolendpointCarPoolCollection : GTLCollectionObject
@property (retain) NSArray *items;  // of GTLCarpoolendpointCarPool
@end
