/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLCarpoolendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   carpoolendpoint/v1
// Description:
//   This is an API

#import "GTLCarpoolendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeCarpoolendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
