/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLCarpoolendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   carpoolendpoint/v1
// Description:
//   This is an API

#import "GTLCarpoolendpointConstants.h"

#import "GTLCarpoolendpointCarPool.h"
#import "GTLCarpoolendpointCarPoolCollection.h"
#import "GTLCarpoolendpointCollectionResponseCarPool.h"

#import "GTLQueryCarpoolendpoint.h"
#import "GTLServiceCarpoolendpoint.h"
