/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLCarpoolendpointCarPoolCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   carpoolendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLCarpoolendpointCarPoolCollection (0 custom class methods, 1 custom properties)

#import "GTLCarpoolendpointCarPoolCollection.h"

#import "GTLCarpoolendpointCarPool.h"

// ----------------------------------------------------------------------------
//
//   GTLCarpoolendpointCarPoolCollection
//

@implementation GTLCarpoolendpointCarPoolCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLCarpoolendpointCarPool class]
                                forKey:@"items"];
  return map;
}

@end
