/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLLocationendpointLocationCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   locationendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLLocationendpointLocationCollection (0 custom class methods, 1 custom properties)

#import "GTLLocationendpointLocationCollection.h"

#import "GTLLocationendpointLocation.h"

// ----------------------------------------------------------------------------
//
//   GTLLocationendpointLocationCollection
//

@implementation GTLLocationendpointLocationCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLLocationendpointLocation class]
                                forKey:@"items"];
  return map;
}

@end
