/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLLocationendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   locationendpoint/v1
// Description:
//   This is an API

#import "GTLLocationendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeLocationendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
