/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLLocationendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   locationendpoint/v1
// Description:
//   This is an API

#import "GTLLocationendpointConstants.h"

#import "GTLLocationendpointCollectionResponseLocation.h"
#import "GTLLocationendpointLocation.h"
#import "GTLLocationendpointLocationCollection.h"

#import "GTLQueryLocationendpoint.h"
#import "GTLServiceLocationendpoint.h"
