/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPassengerendpointPassengerCollection.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   passengerendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPassengerendpointPassengerCollection (0 custom class methods, 1 custom properties)

#import "GTLPassengerendpointPassengerCollection.h"

#import "GTLPassengerendpointPassenger.h"

// ----------------------------------------------------------------------------
//
//   GTLPassengerendpointPassengerCollection
//

@implementation GTLPassengerendpointPassengerCollection
@dynamic items;

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:[GTLPassengerendpointPassenger class]
                                forKey:@"items"];
  return map;
}

@end
