/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPassengerendpointConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   passengerendpoint/v1
// Description:
//   This is an API

#import "GTLPassengerendpointConstants.h"

// Authorization scope
NSString * const kGTLAuthScopePassengerendpointUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
