/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPassengerendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   passengerendpoint/v1
// Description:
//   This is an API

#import "GTLPassengerendpointConstants.h"

#import "GTLPassengerendpointCollectionResponsePassenger.h"
#import "GTLPassengerendpointPassenger.h"
#import "GTLPassengerendpointPassengerCollection.h"

#import "GTLQueryPassengerendpoint.h"
#import "GTLServicePassengerendpoint.h"
