/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPassengerendpointPassenger.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   passengerendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPassengerendpointPassenger (0 custom class methods, 13 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLPassengerendpointPassenger
//

@interface GTLPassengerendpointPassenger : GTLObject
@property (retain) NSNumber *capacity;  // intValue
@property (retain) NSNumber *carPoolId;  // longLongValue

// Remapped to 'descriptionProperty' to avoid NSObject's 'description'.
@property (copy) NSString *descriptionProperty;

@property (copy) NSString *driverComment;
@property (copy) NSString *driverId;

// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (retain) NSNumber *identifier;  // longLongValue

@property (copy) NSString *passengerId;
@property (copy) NSString *passengerName;
@property (retain) NSNumber *pickupLatitude;  // doubleValue
@property (copy) NSString *pickupLocation;
@property (retain) NSNumber *pickupLongitude;  // doubleValue
@property (retain) GTLDateTime *pickupTime;
@property (copy) NSString *status;
@end
