/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLPassengerendpointPassenger.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   passengerendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLPassengerendpointPassenger (0 custom class methods, 13 custom properties)

#import "GTLPassengerendpointPassenger.h"

// ----------------------------------------------------------------------------
//
//   GTLPassengerendpointPassenger
//

@implementation GTLPassengerendpointPassenger
@dynamic capacity, carPoolId, descriptionProperty, driverComment, driverId,
         identifier, passengerId, passengerName, pickupLatitude, pickupLocation,
         pickupLongitude, pickupTime, status;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"description", @"descriptionProperty",
      @"id", @"identifier",
      nil];
  return map;
}

@end
