/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryAssociateendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   associateendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryAssociateendpoint (6 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLAssociateendpointAssociate;

@interface GTLQueryAssociateendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *cernerId;
@property (copy) NSString *cursor;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (assign) long long identifier;
@property (assign) NSInteger limit;

#pragma mark -
#pragma mark "associateEndpoint" methods
// These create a GTLQueryAssociateendpoint object.

// Method: associateendpoint.associateEndpoint.getAssociateById
//  Authorization scope(s):
//   kGTLAuthScopeAssociateendpointUserinfoEmail
// Fetches a GTLAssociateendpointAssociate.
+ (id)queryForAssociateEndpointGetAssociateByIdWithCernerId:(NSString *)cernerId;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryAssociateendpoint object.

// Method: associateendpoint.getAssociate
//  Authorization scope(s):
//   kGTLAuthScopeAssociateendpointUserinfoEmail
// Fetches a GTLAssociateendpointAssociate.
+ (id)queryForGetAssociateWithIdentifier:(long long)identifier;

// Method: associateendpoint.insertAssociate
//  Authorization scope(s):
//   kGTLAuthScopeAssociateendpointUserinfoEmail
// Fetches a GTLAssociateendpointAssociate.
+ (id)queryForInsertAssociateWithObject:(GTLAssociateendpointAssociate *)object;

// Method: associateendpoint.listAssociate
//  Optional:
//   cursor: NSString
//   limit: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopeAssociateendpointUserinfoEmail
// Fetches a GTLAssociateendpointCollectionResponseAssociate.
+ (id)queryForListAssociate;

// Method: associateendpoint.removeAssociate
//  Authorization scope(s):
//   kGTLAuthScopeAssociateendpointUserinfoEmail
+ (id)queryForRemoveAssociateWithIdentifier:(long long)identifier;

// Method: associateendpoint.updateAssociate
//  Authorization scope(s):
//   kGTLAuthScopeAssociateendpointUserinfoEmail
// Fetches a GTLAssociateendpointAssociate.
+ (id)queryForUpdateAssociateWithObject:(GTLAssociateendpointAssociate *)object;

@end
