/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryPassengerendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   passengerendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryPassengerendpoint (8 custom class methods, 7 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLPassengerendpointPassenger;

@interface GTLQueryPassengerendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (assign) long long carPoolId;
@property (copy) NSString *cursor;
@property (copy) NSString *driverId;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (assign) long long identifier;
@property (assign) NSInteger limit;
@property (copy) NSString *passengerId;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryPassengerendpoint object.

// Method: passengerendpoint.getPassenger
//  Authorization scope(s):
//   kGTLAuthScopePassengerendpointUserinfoEmail
// Fetches a GTLPassengerendpointPassenger.
+ (id)queryForGetPassengerWithIdentifier:(long long)identifier;

// Method: passengerendpoint.insertPassenger
//  Authorization scope(s):
//   kGTLAuthScopePassengerendpointUserinfoEmail
// Fetches a GTLPassengerendpointPassenger.
+ (id)queryForInsertPassengerWithObject:(GTLPassengerendpointPassenger *)object;

// Method: passengerendpoint.listPassenger
//  Optional:
//   cursor: NSString
//   limit: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopePassengerendpointUserinfoEmail
// Fetches a GTLPassengerendpointCollectionResponsePassenger.
+ (id)queryForListPassenger;

#pragma mark -
#pragma mark "passengerEndpoint" methods
// These create a GTLQueryPassengerendpoint object.

// Method: passengerendpoint.passengerEndpoint.getPassengerByCarPoolId
//  Authorization scope(s):
//   kGTLAuthScopePassengerendpointUserinfoEmail
// Fetches a GTLPassengerendpointPassengerCollection.
+ (id)queryForPassengerEndpointGetPassengerByCarPoolIdWithCarPoolId:(long long)carPoolId;

// Method: passengerendpoint.passengerEndpoint.getPassengerByDriverId
//  Authorization scope(s):
//   kGTLAuthScopePassengerendpointUserinfoEmail
// Fetches a GTLPassengerendpointPassengerCollection.
+ (id)queryForPassengerEndpointGetPassengerByDriverIdWithDriverId:(NSString *)driverId;

// Method: passengerendpoint.passengerEndpoint.getPassengerByPassengerId
//  Authorization scope(s):
//   kGTLAuthScopePassengerendpointUserinfoEmail
// Fetches a GTLPassengerendpointPassengerCollection.
+ (id)queryForPassengerEndpointGetPassengerByPassengerIdWithPassengerId:(NSString *)passengerId;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryPassengerendpoint object.

// Method: passengerendpoint.removePassenger
//  Authorization scope(s):
//   kGTLAuthScopePassengerendpointUserinfoEmail
+ (id)queryForRemovePassengerWithIdentifier:(long long)identifier;

// Method: passengerendpoint.updatePassenger
//  Authorization scope(s):
//   kGTLAuthScopePassengerendpointUserinfoEmail
// Fetches a GTLPassengerendpointPassenger.
+ (id)queryForUpdatePassengerWithObject:(GTLPassengerendpointPassenger *)object;

@end
