/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryLocationendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   locationendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryLocationendpoint (6 custom class methods, 5 custom properties)

#import "GTLQueryLocationendpoint.h"

#import "GTLLocationendpointCollectionResponseLocation.h"
#import "GTLLocationendpointLocation.h"
#import "GTLLocationendpointLocationCollection.h"

@implementation GTLQueryLocationendpoint

@dynamic associateId, cursor, fields, identifier, limit;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryLocationendpoint object.

+ (id)queryForGetLocationWithIdentifier:(long long)identifier {
  NSString *methodName = @"locationendpoint.getLocation";
  GTLQueryLocationendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLLocationendpointLocation class];
  return query;
}

+ (id)queryForInsertLocationWithObject:(GTLLocationendpointLocation *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"locationendpoint.insertLocation";
  GTLQueryLocationendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLLocationendpointLocation class];
  return query;
}

+ (id)queryForListLocation {
  NSString *methodName = @"locationendpoint.listLocation";
  GTLQueryLocationendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLLocationendpointCollectionResponseLocation class];
  return query;
}

#pragma mark -
#pragma mark "locationEndpoint" methods
// These create a GTLQueryLocationendpoint object.

+ (id)queryForLocationEndpointGetLocationByAssoicateIdWithAssociateId:(NSString *)associateId {
  NSString *methodName = @"locationendpoint.locationEndpoint.getLocationByAssoicateId";
  GTLQueryLocationendpoint *query = [self queryWithMethodName:methodName];
  query.associateId = associateId;
  query.expectedObjectClass = [GTLLocationendpointLocationCollection class];
  return query;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryLocationendpoint object.

+ (id)queryForRemoveLocationWithIdentifier:(long long)identifier {
  NSString *methodName = @"locationendpoint.removeLocation";
  GTLQueryLocationendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  return query;
}

+ (id)queryForUpdateLocationWithObject:(GTLLocationendpointLocation *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"locationendpoint.updateLocation";
  GTLQueryLocationendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLLocationendpointLocation class];
  return query;
}

@end
