/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryAssociateendpoint.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   associateendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryAssociateendpoint (6 custom class methods, 5 custom properties)

#import "GTLQueryAssociateendpoint.h"

#import "GTLAssociateendpointAssociate.h"
#import "GTLAssociateendpointCollectionResponseAssociate.h"

@implementation GTLQueryAssociateendpoint

@dynamic cernerId, cursor, fields, identifier, limit;

+ (NSDictionary *)parameterNameMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"id"
                                forKey:@"identifier"];
  return map;
}

#pragma mark -
#pragma mark "associateEndpoint" methods
// These create a GTLQueryAssociateendpoint object.

+ (id)queryForAssociateEndpointGetAssociateByIdWithCernerId:(NSString *)cernerId {
  NSString *methodName = @"associateendpoint.associateEndpoint.getAssociateById";
  GTLQueryAssociateendpoint *query = [self queryWithMethodName:methodName];
  query.cernerId = cernerId;
  query.expectedObjectClass = [GTLAssociateendpointAssociate class];
  return query;
}

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryAssociateendpoint object.

+ (id)queryForGetAssociateWithIdentifier:(long long)identifier {
  NSString *methodName = @"associateendpoint.getAssociate";
  GTLQueryAssociateendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  query.expectedObjectClass = [GTLAssociateendpointAssociate class];
  return query;
}

+ (id)queryForInsertAssociateWithObject:(GTLAssociateendpointAssociate *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"associateendpoint.insertAssociate";
  GTLQueryAssociateendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLAssociateendpointAssociate class];
  return query;
}

+ (id)queryForListAssociate {
  NSString *methodName = @"associateendpoint.listAssociate";
  GTLQueryAssociateendpoint *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLAssociateendpointCollectionResponseAssociate class];
  return query;
}

+ (id)queryForRemoveAssociateWithIdentifier:(long long)identifier {
  NSString *methodName = @"associateendpoint.removeAssociate";
  GTLQueryAssociateendpoint *query = [self queryWithMethodName:methodName];
  query.identifier = identifier;
  return query;
}

+ (id)queryForUpdateAssociateWithObject:(GTLAssociateendpointAssociate *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"associateendpoint.updateAssociate";
  GTLQueryAssociateendpoint *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLAssociateendpointAssociate class];
  return query;
}

@end
