/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2014 Google Inc.
 */

//
//  GTLQueryLocationendpoint.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   locationendpoint/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryLocationendpoint (6 custom class methods, 5 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLLocationendpointLocation;

@interface GTLQueryLocationendpoint : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

//
// Method-specific parameters; see the comments below for more information.
//
@property (copy) NSString *associateId;
@property (copy) NSString *cursor;
// identifier property maps to 'id' in JSON (to avoid Objective C's 'id').
@property (assign) long long identifier;
@property (assign) NSInteger limit;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryLocationendpoint object.

// Method: locationendpoint.getLocation
//  Authorization scope(s):
//   kGTLAuthScopeLocationendpointUserinfoEmail
// Fetches a GTLLocationendpointLocation.
+ (id)queryForGetLocationWithIdentifier:(long long)identifier;

// Method: locationendpoint.insertLocation
//  Authorization scope(s):
//   kGTLAuthScopeLocationendpointUserinfoEmail
// Fetches a GTLLocationendpointLocation.
+ (id)queryForInsertLocationWithObject:(GTLLocationendpointLocation *)object;

// Method: locationendpoint.listLocation
//  Optional:
//   cursor: NSString
//   limit: NSInteger
//  Authorization scope(s):
//   kGTLAuthScopeLocationendpointUserinfoEmail
// Fetches a GTLLocationendpointCollectionResponseLocation.
+ (id)queryForListLocation;

#pragma mark -
#pragma mark "locationEndpoint" methods
// These create a GTLQueryLocationendpoint object.

// Method: locationendpoint.locationEndpoint.getLocationByAssoicateId
//  Authorization scope(s):
//   kGTLAuthScopeLocationendpointUserinfoEmail
// Fetches a GTLLocationendpointLocationCollection.
+ (id)queryForLocationEndpointGetLocationByAssoicateIdWithAssociateId:(NSString *)associateId;

#pragma mark -
#pragma mark Service level methods
// These create a GTLQueryLocationendpoint object.

// Method: locationendpoint.removeLocation
//  Authorization scope(s):
//   kGTLAuthScopeLocationendpointUserinfoEmail
+ (id)queryForRemoveLocationWithIdentifier:(long long)identifier;

// Method: locationendpoint.updateLocation
//  Authorization scope(s):
//   kGTLAuthScopeLocationendpointUserinfoEmail
// Fetches a GTLLocationendpointLocation.
+ (id)queryForUpdateLocationWithObject:(GTLLocationendpointLocation *)object;

@end
